version: "3.9"
services:
  db:
    container_name: dongalab-db
    image: "postgres:14"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dongalab
    volumes:
      - ./data:/var/lib/postgresql/data
  admin:
    container_name: dongalab-admin
    image: "matenemeth/dongalab-admin"
    environment:
      DATABASE_URL: postgres://postgres:postgres@dongalab-db:5432/dongalab
      VIRTUAL_HOST: admin.dongalab.hu
      LETSENCRYPT_HOST: admin.dongalab.hu
      VIRTUAL_PORT: 80

networks:
  default:
    name: net
    external: true